version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxytest
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-usertest
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feedtest
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontendtest:local