apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        api: external        
    spec:
      containers:
      - image: bichoydemiane/udagram-frontendtest:v1
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.2"
          limits:
            memory: "2048Mi"
            cpu: "2"                
      restartPolicy: Always